version: '3'

services:
  app_tests:
    build: .
    volumes:
      - .:/project
    command: ceedling

  app:
    build: .
    depends_on: 
      - app_tests
    volumes:
      - .:/project
    command: idf.py build
  